#Path to the input list
input_list: "/path/to/input/input_list.tsv"   #List of input files and metadata

#Desired flanking region length 
flank_length: "10000"

#dRep parameters
drep_pc: "0.99"       #Primary clustering threshold for MASH
drep_sc: "0.95"       #Secondary clustering threshold

#Prokka "Genus" for Annotaring Genomes
genus:  "Escherichia"

#portions of genes to analyse (e.g 3 = one third of genes)
slice_size: "1"

#K-mer size for KMA distance calculation
k-mer_size: "16" 

