name: my_pipeline
channels:
  - nodefaults
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - tabulate=0.8.10
  - snakemake=6.9.1
  - seqkit=2.1.0
  - blast=2.12.0
  - perl=5.26.2
  - perl-bioperl=1.7.2
  - perl-bioperl-core=1.7.2
  - bedtools=2.27.1
  - kma=1.4.0
  - cd-hit=4.6.8
  - prokka=1.14.6
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - r-ape=5.6
  - roary=3.13.0
  - r-vegan
  - r-reshape2
  - mcl=14-137
  - parallel=20180522
  - prank
  - mafft
  - fasttree
  - fastani

